name: fn_express

description: A Dart package for parsing and evaluating mathematical expressions
  with support for variables, functions, constants, expression simplification,
  and symbolic differentiation.

version: 2.1.3

homepage: https://github.com/hamed-rezaee/fn_express

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  linter: any
  test: any
