name: fn_express

description: A Dart package for parsing and evaluating mathematical expressions with support for variables, functions, and constants.
version: 1.1.3

homepage: https://github.com/hamed-rezaee/fn_express

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^9.0.0
